In [39]:
import sys

print(sys.executable)

c:\Documents\Desktop\Fintech_Api-Pipeline\venv\Scripts\python.exe

### Import the Libraries

In [40]:
import os
from datetime import datetime, timezone

import pandas as pd

import requests

from dotenv import load_dotenv

from sqlalchemy import create_engine, text

In [41]:
# load environment variables from .env file
load_dotenv()

True

### Define API endpoints/configuration

In [42]:
BASE_CURRENCY = "USD"
API_URL = (f"https://open.er-api.com/v6/latest/{BASE_CURRENCY}")

print(API_URL)

https://open.er-api.com/v6/latest/USD

### Extraction

In [43]:
response = requests.get(API_URL, timeout=30)

print("status code:", response.status_code)
response.raise_for_status()  # Raise an exception for HTTP errors

api_data = response.json()

print(api_data["result"])
print(api_data["base_code"])

status code: 200
success
USD

In [44]:
# Inspect the complete JSON response to understand its structure
api_data  # This will display the entire JSON response in the notebook

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1784332952,
 'time_last_update_utc': 'Sat, 18 Jul 2026 00:02:32 +0000',
 'time_next_update_unix': 1784421102,
 'time_next_update_utc': 'Sun, 19 Jul 2026 00:31:42 +0000',
 'time_eol_unix': 0,
 'base_code': 'USD',
 'rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 66.008291,
  'ALL': 81.852701,
  'AMD': 366.674156,
  'ANG': 1.79,
  'AOA': 926.855963,
  'ARS': 1480.1223,
  'AUD': 1.432241,
  'AWG': 1.79,
  'AZN': 1.699923,
  'BAM': 1.710272,
  'BBD': 2,
  'BDT': 123.245194,
  'BGN': 1.710272,
  'BHD': 0.376,
  'BIF': 2992.642076,
  'BMD': 1,
  'BND': 1.291343,
  'BOB': 10.533892,
  'BRL': 5.1005,
  'BSD': 1,
  'BTN': 96.409744,
  'BWP': 14.045655,
  'BYN': 2.88484,
  'BZD': 2,
  'CAD': 1.401869,
  'CDF': 2272.550711,
  'CHF': 0.807431,
  'CLF': 0.023396,
  'CLP': 924.739337,
  'CNH': 6.777672,
  'CNY': 6.784582,
  'COP': 3225.081918,
  'CRC': 454.018753,
  'CUP': 24,
  'CVE': 96.421037,
  'CZK': 21.157415,
  'DJF': 177.721,
  'DKK': 6.526812,
  'DOP': 58.370612,
  'DZD': 133.061169,
  'EGP': 50.543868,
  'ERN': 15,
  'ETB': 160.889769,
  'EUR': 0.874447,
  'FJD': 2.242714,
  'FKP': 0.743836,
  'FOK': 6.526799,
  'GBP': 0.743836,
  'GEL': 2.631036,
  'GGP': 0.743836,
  'GHS': 11.568737,
  'GIP': 0.743836,
  'GMD': 74.331983,
  'GNF': 8777.194785,
  'GTQ': 7.626168,
  'GYD': 209.22893,
  'HKD': 7.839793,
  'HNL': 26.760604,
  'HRK': 6.58853,
  'HTG': 130.683119,
  'HUF': 316.964202,
  'IDR': 17966.847874,
  'ILS': 3.043199,
  'IMP': 0.743836,
  'INR': 96.410189,
  'IQD': 1309.350203,
  'IRR': 1321355.393317,
  'ISK': 125.325013,
  'JEP': 0.743836,
  'JMD': 158.491921,
  'JOD': 0.709,
  'JPY': 162.400016,
  'KES': 129.326759,
  'KGS': 87.436453,
  'KHR': 4043.804352,
  'KID': 1.43224,
  'KMF': 430.200342,
  'KRW': 1486.872306,
  'KWD': 0.308905,
  'KYD': 0.833333,
  'KZT': 471.743591,
  'LAK': 22288.708825,
  'LBP': 89500,
  'LKR': 336.156459,
  'LRD': 180.99288,
  'LSL': 16.503019,
  'LYD': 6.399804,
  'MAD': 9.335513,
  'MDL': 17.560391,
  'MGA': 4293.710419,
  'MKD': 53.73941,
  'MMK': 2102.499937,
  'MNT': 3621.55412,
  'MOP': 8.074987,
  'MRU': 40.101662,
  'MUR': 47.115342,
  'MVR': 15.448403,
  'MWK': 1745.751526,
  'MXN': 17.524821,
  'MYR': 4.080122,
  'MZN': 63.592459,
  'NAD': 16.503019,
  'NGN': 1380.432792,
  'NIO': 36.782088,
  'NOK': 9.65048,
  'NPR': 154.255591,
  'NZD': 1.711859,
  'OMR': 0.384497,
  'PAB': 1,
  'PEN': 3.396682,
  'PGK': 4.432315,
  'PHP': 61.672002,
  'PKR': 278.013177,
  'PLN': 3.791884,
  'PYG': 6041.083696,
  'QAR': 3.64,
  'RON': 4.582423,
  'RSD': 102.589144,
  'RUB': 77.915921,
  'RWF': 1471.989937,
  'SAR': 3.75,
  'SBD': 7.962499,
  'SCR': 14.707188,
  'SDG': 510.351192,
  'SEK': 9.650066,
  'SGD': 1.291344,
  'SHP': 0.743836,
  'SLE': 24.357914,
  'SLL': 24357.91394,
  'SOS': 571.636809,
  'SRD': 37.85942,
  'SSP': 4842.713916,
  'STN': 21.423982,
  'SYP': 121.909573,
  'SZL': 16.503019,
  'THB': 33.618438,
  'TJS': 9.238577,
  'TMT': 3.499878,
  'TND': 2.948015,
  'TOP': 2.378981,
  'TRY': 47.173144,
  'TTD': 6.756715,
  'TVD': 1.43224,
  'TWD': 32.363505,
  'TZS': 2629.088628,
  'UAH': 44.65453,
  'UGX': 3669.521638,
  'UYU': 40.161314,
  'UZS': 12097.907847,
  'VES': 736.9339,
  'VND': 26203.031344,
  'VUV': 119.59331,
  'WST': 2.707577,
  'XAF': 573.600455,
  'XCD': 2.7,
  'XCG': 1.79,
  'XDR': 0.735737,
  'XOF': 573.600455,
  'XPF': 104.349659,
  'YER': 238.116844,
  'ZAR': 16.502998,
  'ZMW': 18.183446,
  'ZWG': 26.6848,
  'ZWL': 26.6848}}

In [45]:
# Extract the business data out of the main JSON output
api_data["rates"]  # This will display the exchange rates data in the notebook

{'USD': 1,
 'AED': 3.6725,
 'AFN': 66.008291,
 'ALL': 81.852701,
 'AMD': 366.674156,
 'ANG': 1.79,
 'AOA': 926.855963,
 'ARS': 1480.1223,
 'AUD': 1.432241,
 'AWG': 1.79,
 'AZN': 1.699923,
 'BAM': 1.710272,
 'BBD': 2,
 'BDT': 123.245194,
 'BGN': 1.710272,
 'BHD': 0.376,
 'BIF': 2992.642076,
 'BMD': 1,
 'BND': 1.291343,
 'BOB': 10.533892,
 'BRL': 5.1005,
 'BSD': 1,
 'BTN': 96.409744,
 'BWP': 14.045655,
 'BYN': 2.88484,
 'BZD': 2,
 'CAD': 1.401869,
 'CDF': 2272.550711,
 'CHF': 0.807431,
 'CLF': 0.023396,
 'CLP': 924.739337,
 'CNH': 6.777672,
 'CNY': 6.784582,
 'COP': 3225.081918,
 'CRC': 454.018753,
 'CUP': 24,
 'CVE': 96.421037,
 'CZK': 21.157415,
 'DJF': 177.721,
 'DKK': 6.526812,
 'DOP': 58.370612,
 'DZD': 133.061169,
 'EGP': 50.543868,
 'ERN': 15,
 'ETB': 160.889769,
 'EUR': 0.874447,
 'FJD': 2.242714,
 'FKP': 0.743836,
 'FOK': 6.526799,
 'GBP': 0.743836,
 'GEL': 2.631036,
 'GGP': 0.743836,
 'GHS': 11.568737,
 'GIP': 0.743836,
 'GMD': 74.331983,
 'GNF': 8777.194785,
 'GTQ': 7.626168,
 'GYD': 209.22893,
 'HKD': 7.839793,
 'HNL': 26.760604,
 'HRK': 6.58853,
 'HTG': 130.683119,
 'HUF': 316.964202,
 'IDR': 17966.847874,
 'ILS': 3.043199,
 'IMP': 0.743836,
 'INR': 96.410189,
 'IQD': 1309.350203,
 'IRR': 1321355.393317,
 'ISK': 125.325013,
 'JEP': 0.743836,
 'JMD': 158.491921,
 'JOD': 0.709,
 'JPY': 162.400016,
 'KES': 129.326759,
 'KGS': 87.436453,
 'KHR': 4043.804352,
 'KID': 1.43224,
 'KMF': 430.200342,
 'KRW': 1486.872306,
 'KWD': 0.308905,
 'KYD': 0.833333,
 'KZT': 471.743591,
 'LAK': 22288.708825,
 'LBP': 89500,
 'LKR': 336.156459,
 'LRD': 180.99288,
 'LSL': 16.503019,
 'LYD': 6.399804,
 'MAD': 9.335513,
 'MDL': 17.560391,
 'MGA': 4293.710419,
 'MKD': 53.73941,
 'MMK': 2102.499937,
 'MNT': 3621.55412,
 'MOP': 8.074987,
 'MRU': 40.101662,
 'MUR': 47.115342,
 'MVR': 15.448403,
 'MWK': 1745.751526,
 'MXN': 17.524821,
 'MYR': 4.080122,
 'MZN': 63.592459,
 'NAD': 16.503019,
 'NGN': 1380.432792,
 'NIO': 36.782088,
 'NOK': 9.65048,
 'NPR': 154.255591,
 'NZD': 1.711859,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.396682,
 'PGK': 4.432315,
 'PHP': 61.672002,
 'PKR': 278.013177,
 'PLN': 3.791884,
 'PYG': 6041.083696,
 'QAR': 3.64,
 'RON': 4.582423,
 'RSD': 102.589144,
 'RUB': 77.915921,
 'RWF': 1471.989937,
 'SAR': 3.75,
 'SBD': 7.962499,
 'SCR': 14.707188,
 'SDG': 510.351192,
 'SEK': 9.650066,
 'SGD': 1.291344,
 'SHP': 0.743836,
 'SLE': 24.357914,
 'SLL': 24357.91394,
 'SOS': 571.636809,
 'SRD': 37.85942,
 'SSP': 4842.713916,
 'STN': 21.423982,
 'SYP': 121.909573,
 'SZL': 16.503019,
 'THB': 33.618438,
 'TJS': 9.238577,
 'TMT': 3.499878,
 'TND': 2.948015,
 'TOP': 2.378981,
 'TRY': 47.173144,
 'TTD': 6.756715,
 'TVD': 1.43224,
 'TWD': 32.363505,
 'TZS': 2629.088628,
 'UAH': 44.65453,
 'UGX': 3669.521638,
 'UYU': 40.161314,
 'UZS': 12097.907847,
 'VES': 736.9339,
 'VND': 26203.031344,
 'VUV': 119.59331,
 'WST': 2.707577,
 'XAF': 573.600455,
 'XCD': 2.7,
 'XCG': 1.79,
 'XDR': 0.735737,
 'XOF': 573.600455,
 'XPF': 104.349659,
 'YER': 238.116844,
 'ZAR': 16.502998,
 'ZMW': 18.183446,
 'ZWG': 26.6848,
 'ZWL': 26.6848}

In [46]:
type(api_data["rates"])  # This will show the type of the extracted rates data

dict

In [47]:
api_data.keys()  # This will display the keys of the main JSON response

dict_keys(['result', 'provider', 'documentation', 'terms_of_use', 'time_last_update_unix', 'time_last_update_utc', 'time_next_update_unix', 'time_next_update_utc', 'time_eol_unix', 'base_code', 'rates'])

### save the raw API response

In [48]:
import json 
from pathlib import Path

raw_folder = Path("../data/raw_data") 

raw_folder.mkdir(parents=True, exist_ok=True)

extraction_timestamp = datetime.now(timezone.utc)

raw_filename = (
    f"exchange_rates_"
    f"{extraction_timestamp:%Y%m%d_%H%M%S}.json"
) 

raw_path = raw_folder / raw_filename

with open(raw_path, "w", encoding="utf-8") as file:
    json.dump(api_data, file, indent=4) 
    
print(f"Raw response saved to: {raw_path}")

Raw response saved to: ..\data\raw_data\exchange_rates_20260718_202129.json

### Transformation

In [61]:
# Extract the business data 
rates = api_data["rates"]

# Display the data
rates

{'USD': 1,
 'AED': 3.6725,
 'AFN': 66.008291,
 'ALL': 81.852701,
 'AMD': 366.674156,
 'ANG': 1.79,
 'AOA': 926.855963,
 'ARS': 1480.1223,
 'AUD': 1.432241,
 'AWG': 1.79,
 'AZN': 1.699923,
 'BAM': 1.710272,
 'BBD': 2,
 'BDT': 123.245194,
 'BGN': 1.710272,
 'BHD': 0.376,
 'BIF': 2992.642076,
 'BMD': 1,
 'BND': 1.291343,
 'BOB': 10.533892,
 'BRL': 5.1005,
 'BSD': 1,
 'BTN': 96.409744,
 'BWP': 14.045655,
 'BYN': 2.88484,
 'BZD': 2,
 'CAD': 1.401869,
 'CDF': 2272.550711,
 'CHF': 0.807431,
 'CLF': 0.023396,
 'CLP': 924.739337,
 'CNH': 6.777672,
 'CNY': 6.784582,
 'COP': 3225.081918,
 'CRC': 454.018753,
 'CUP': 24,
 'CVE': 96.421037,
 'CZK': 21.157415,
 'DJF': 177.721,
 'DKK': 6.526812,
 'DOP': 58.370612,
 'DZD': 133.061169,
 'EGP': 50.543868,
 'ERN': 15,
 'ETB': 160.889769,
 'EUR': 0.874447,
 'FJD': 2.242714,
 'FKP': 0.743836,
 'FOK': 6.526799,
 'GBP': 0.743836,
 'GEL': 2.631036,
 'GGP': 0.743836,
 'GHS': 11.568737,
 'GIP': 0.743836,
 'GMD': 74.331983,
 'GNF': 8777.194785,
 'GTQ': 7.626168,
 'GYD': 209.22893,
 'HKD': 7.839793,
 'HNL': 26.760604,
 'HRK': 6.58853,
 'HTG': 130.683119,
 'HUF': 316.964202,
 'IDR': 17966.847874,
 'ILS': 3.043199,
 'IMP': 0.743836,
 'INR': 96.410189,
 'IQD': 1309.350203,
 'IRR': 1321355.393317,
 'ISK': 125.325013,
 'JEP': 0.743836,
 'JMD': 158.491921,
 'JOD': 0.709,
 'JPY': 162.400016,
 'KES': 129.326759,
 'KGS': 87.436453,
 'KHR': 4043.804352,
 'KID': 1.43224,
 'KMF': 430.200342,
 'KRW': 1486.872306,
 'KWD': 0.308905,
 'KYD': 0.833333,
 'KZT': 471.743591,
 'LAK': 22288.708825,
 'LBP': 89500,
 'LKR': 336.156459,
 'LRD': 180.99288,
 'LSL': 16.503019,
 'LYD': 6.399804,
 'MAD': 9.335513,
 'MDL': 17.560391,
 'MGA': 4293.710419,
 'MKD': 53.73941,
 'MMK': 2102.499937,
 'MNT': 3621.55412,
 'MOP': 8.074987,
 'MRU': 40.101662,
 'MUR': 47.115342,
 'MVR': 15.448403,
 'MWK': 1745.751526,
 'MXN': 17.524821,
 'MYR': 4.080122,
 'MZN': 63.592459,
 'NAD': 16.503019,
 'NGN': 1380.432792,
 'NIO': 36.782088,
 'NOK': 9.65048,
 'NPR': 154.255591,
 'NZD': 1.711859,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.396682,
 'PGK': 4.432315,
 'PHP': 61.672002,
 'PKR': 278.013177,
 'PLN': 3.791884,
 'PYG': 6041.083696,
 'QAR': 3.64,
 'RON': 4.582423,
 'RSD': 102.589144,
 'RUB': 77.915921,
 'RWF': 1471.989937,
 'SAR': 3.75,
 'SBD': 7.962499,
 'SCR': 14.707188,
 'SDG': 510.351192,
 'SEK': 9.650066,
 'SGD': 1.291344,
 'SHP': 0.743836,
 'SLE': 24.357914,
 'SLL': 24357.91394,
 'SOS': 571.636809,
 'SRD': 37.85942,
 'SSP': 4842.713916,
 'STN': 21.423982,
 'SYP': 121.909573,
 'SZL': 16.503019,
 'THB': 33.618438,
 'TJS': 9.238577,
 'TMT': 3.499878,
 'TND': 2.948015,
 'TOP': 2.378981,
 'TRY': 47.173144,
 'TTD': 6.756715,
 'TVD': 1.43224,
 'TWD': 32.363505,
 'TZS': 2629.088628,
 'UAH': 44.65453,
 'UGX': 3669.521638,
 'UYU': 40.161314,
 'UZS': 12097.907847,
 'VES': 736.9339,
 'VND': 26203.031344,
 'VUV': 119.59331,
 'WST': 2.707577,
 'XAF': 573.600455,
 'XCD': 2.7,
 'XCG': 1.79,
 'XDR': 0.735737,
 'XOF': 573.600455,
 'XPF': 104.349659,
 'YER': 238.116844,
 'ZAR': 16.502998,
 'ZMW': 18.183446,
 'ZWG': 26.6848,
 'ZWL': 26.6848}

In [62]:
# convert the rates dictionary to a DataFrame
exchange_rates = pd.DataFrame(list(rates.items()),columns=["currency", "exchange_rate"])
exchange_rates.head(10)  # Display the first few rows of the DataFrame

  currency  exchange_rate
0      USD       1.000000
1      AED       3.672500
2      AFN      66.008291
3      ALL      81.852701
4      AMD     366.674156
5      ANG       1.790000
6      AOA     926.855963
7      ARS    1480.122300
8      AUD       1.432241
9      AWG       1.790000

In [63]:
# Add base currency to every row
exchange_rates["base_currency"] = api_data["base_code"]

exchange_rates.head(10)

  currency  exchange_rate base_currency
0      USD       1.000000           USD
1      AED       3.672500           USD
2      AFN      66.008291           USD
3      ALL      81.852701           USD
4      AMD     366.674156           USD
5      ANG       1.790000           USD
6      AOA     926.855963           USD
7      ARS    1480.122300           USD
8      AUD       1.432241           USD
9      AWG       1.790000           USD

In [64]:
# Add extraction timestamp
exchange_rates["retrieved_at"] = api_data["time_last_update_utc"]

exchange_rates.head()

  currency  exchange_rate base_currency                     retrieved_at
0      USD       1.000000           USD  Sat, 18 Jul 2026 00:02:32 +0000
1      AED       3.672500           USD  Sat, 18 Jul 2026 00:02:32 +0000
2      AFN      66.008291           USD  Sat, 18 Jul 2026 00:02:32 +0000
3      ALL      81.852701           USD  Sat, 18 Jul 2026 00:02:32 +0000
4      AMD     366.674156           USD  Sat, 18 Jul 2026 00:02:32 +0000

In [65]:
exchange_rates

    currency  exchange_rate base_currency                     retrieved_at
0        USD       1.000000           USD  Sat, 18 Jul 2026 00:02:32 +0000
1        AED       3.672500           USD  Sat, 18 Jul 2026 00:02:32 +0000
2        AFN      66.008291           USD  Sat, 18 Jul 2026 00:02:32 +0000
3        ALL      81.852701           USD  Sat, 18 Jul 2026 00:02:32 +0000
4        AMD     366.674156           USD  Sat, 18 Jul 2026 00:02:32 +0000
..       ...            ...           ...                              ...
161      YER     238.116844           USD  Sat, 18 Jul 2026 00:02:32 +0000
162      ZAR      16.502998           USD  Sat, 18 Jul 2026 00:02:32 +0000
163      ZMW      18.183446           USD  Sat, 18 Jul 2026 00:02:32 +0000
164      ZWG      26.684800           USD  Sat, 18 Jul 2026 00:02:32 +0000
165      ZWL      26.684800           USD  Sat, 18 Jul 2026 00:02:32 +0000

[166 rows x 4 columns]

In [67]:
# Rearrange the columns 
exchange_rates = exchange_rates[ 
    [               
        "base_currency",
        "currency",
        "exchange_rate",
        "retrieved_at"
    ]
]

exchange_rates.head()

  base_currency currency  exchange_rate                     retrieved_at
0           USD      USD       1.000000  Sat, 18 Jul 2026 00:02:32 +0000
1           USD      AED       3.672500  Sat, 18 Jul 2026 00:02:32 +0000
2           USD      AFN      66.008291  Sat, 18 Jul 2026 00:02:32 +0000
3           USD      ALL      81.852701  Sat, 18 Jul 2026 00:02:32 +0000
4           USD      AMD     366.674156  Sat, 18 Jul 2026 00:02:32 +0000

In [68]:
exchange_rates.shape

(166, 4)

In [69]:
exchange_rates.dtypes

base_currency        str
currency             str
exchange_rate    float64
retrieved_at         str
dtype: object