In [2]:
import sys

print(sys.executable)

c:\Documents\Desktop\Fintech_Api-Pipeline\venv\Scripts\python.exe

### Import the Libraries

In [3]:
import os
from datetime import datetime, timezone

import pandas as pd

import requests

from dotenv import load_dotenv

from sqlalchemy import create_engine, text

In [4]:
# load environment variables from .env file
load_dotenv()

True

### Define API endpoints/configuration

In [5]:
BASE_CURRENCY = "USD"
API_URL = (f"https://open.er-api.com/v6/latest/{BASE_CURRENCY}")

print(API_URL)

https://open.er-api.com/v6/latest/USD

### Extraction

In [6]:
response = requests.get(API_URL, timeout=30)

print("status code:", response.status_code)
response.raise_for_status()  # Raise an exception for HTTP errors

api_data = response.json()

print(api_data["result"])
print(api_data["base_code"])

status code: 200
success
USD

In [7]:
# Inspect the complete JSON response to understand its structure
api_data  # This will display the entire JSON response in the notebook

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1784678551,
 'time_last_update_utc': 'Wed, 22 Jul 2026 00:02:31 +0000',
 'time_next_update_unix': 1784766381,
 'time_next_update_utc': 'Thu, 23 Jul 2026 00:26:21 +0000',
 'time_eol_unix': 0,
 'base_code': 'USD',
 'rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 66.297576,
  'ALL': 82.088135,
  'AMD': 366.257897,
  'ANG': 1.79,
  'AOA': 929.484375,
  'ARS': 1477.7,
  'AUD': 1.428082,
  'AWG': 1.79,
  'AZN': 1.700145,
  'BAM': 1.714692,
  'BBD': 2,
  'BDT': 123.355712,
  'BGN': 1.714692,
  'BHD': 0.376,
  'BIF': 2992.937831,
  'BMD': 1,
  'BND': 1.291586,
  'BOB': 10.775878,
  'BRL': 5.077823,
  'BSD': 1,
  'BTN': 96.337696,
  'BWP': 14.390566,
  'BYN': 2.889388,
  'BZD': 2,
  'CAD': 1.409459,
  'CDF': 2277.763814,
  'CHF': 0.812218,
  'CLF': 0.023647,
  'CLP': 934.68866,
  'CNH': 6.767975,
  'CNY': 6.776686,
  'COP': 3250.798233,
  'CRC': 454.027923,
  'CUP': 24,
  'CVE': 96.670222,
  'CZK': 21.205386,
  'DJF': 177.721,
  'DKK': 6.542063,
  'DOP': 58.487939,
  'DZD': 133.229912,
  'EGP': 51.008475,
  'ERN': 15,
  'ETB': 160.33367,
  'EUR': 0.876691,
  'FJD': 2.22223,
  'FKP': 0.747079,
  'FOK': 6.542109,
  'GBP': 0.747063,
  'GEL': 2.627584,
  'GGP': 0.747079,
  'GHS': 11.594989,
  'GIP': 0.747079,
  'GMD': 74.412388,
  'GNF': 8782.205095,
  'GTQ': 7.631616,
  'GYD': 209.179097,
  'HKD': 7.842023,
  'HNL': 26.799781,
  'HRK': 6.605557,
  'HTG': 130.667411,
  'HUF': 316.957688,
  'IDR': 17905.298943,
  'ILS': 3.048643,
  'IMP': 0.747079,
  'INR': 96.339012,
  'IQD': 1309.378705,
  'IRR': 1353382.13832,
  'ISK': 125.226659,
  'JEP': 0.747079,
  'JMD': 158.627294,
  'JOD': 0.709,
  'JPY': 163.013007,
  'KES': 129.382422,
  'KGS': 87.451377,
  'KHR': 4048.568017,
  'KID': 1.42808,
  'KMF': 431.312127,
  'KRW': 1480.020746,
  'KWD': 0.309775,
  'KYD': 0.833333,
  'KZT': 468.495614,
  'LAK': 22431.530479,
  'LBP': 89500,
  'LKR': 336.190656,
  'LRD': 181.167029,
  'LSL': 16.461323,
  'LYD': 6.393734,
  'MAD': 9.378687,
  'MDL': 17.567872,
  'MGA': 4314.993562,
  'MKD': 53.842037,
  'MMK': 2102.646218,
  'MNT': 3607.087356,
  'MOP': 8.077185,
  'MRU': 40.059953,
  'MUR': 47.220323,
  'MVR': 15.448708,
  'MWK': 1745.497087,
  'MXN': 17.404263,
  'MYR': 4.088918,
  'MZN': 63.562138,
  'NAD': 16.461323,
  'NGN': 1377.172985,
  'NIO': 36.821579,
  'NOK': 9.633253,
  'NPR': 154.140313,
  'NZD': 1.715316,
  'OMR': 0.384497,
  'PAB': 1,
  'PEN': 3.397041,
  'PGK': 4.47379,
  'PHP': 61.778739,
  'PKR': 278.003,
  'PLN': 3.794625,
  'PYG': 6055.67788,
  'QAR': 3.64,
  'RON': 4.588323,
  'RSD': 102.780119,
  'RUB': 78.486585,
  'RWF': 1471.350212,
  'SAR': 3.75,
  'SBD': 7.96279,
  'SCR': 14.000401,
  'SDG': 449.443084,
  'SEK': 9.699263,
  'SGD': 1.291588,
  'SHP': 0.747079,
  'SLE': 24.357914,
  'SLL': 24357.91394,
  'SOS': 571.930366,
  'SRD': 37.751053,
  'SSP': 4850.71167,
  'STN': 21.479349,
  'SYP': 121.76991,
  'SZL': 16.461323,
  'THB': 33.69783,
  'TJS': 9.238437,
  'TMT': 3.499985,
  'TND': 2.947032,
  'TOP': 2.38493,
  'TRY': 47.203836,
  'TTD': 6.768211,
  'TVD': 1.42808,
  'TWD': 32.34328,
  'TZS': 2628.102311,
  'UAH': 44.775914,
  'UGX': 3692.47881,
  'UYU': 40.270807,
  'UZS': 11930.641883,
  'VES': 737.2321,
  'VND': 26238.632049,
  'VUV': 118.972771,
  'WST': 2.706612,
  'XAF': 575.082836,
  'XCD': 2.7,
  'XCG': 1.79,
  'XDR': 0.7357,
  'XOF': 575.082836,
  'XPF': 104.619335,
  'YER': 238.142523,
  'ZAR': 16.461425,
  'ZMW': 18.372644,
  'ZWG': 26.7962,
  'ZWL': 26.7962}}

In [8]:
# Extract the business data out of the main JSON output
api_data["rates"]  # This will display the exchange rates data in the notebook

{'USD': 1,
 'AED': 3.6725,
 'AFN': 66.297576,
 'ALL': 82.088135,
 'AMD': 366.257897,
 'ANG': 1.79,
 'AOA': 929.484375,
 'ARS': 1477.7,
 'AUD': 1.428082,
 'AWG': 1.79,
 'AZN': 1.700145,
 'BAM': 1.714692,
 'BBD': 2,
 'BDT': 123.355712,
 'BGN': 1.714692,
 'BHD': 0.376,
 'BIF': 2992.937831,
 'BMD': 1,
 'BND': 1.291586,
 'BOB': 10.775878,
 'BRL': 5.077823,
 'BSD': 1,
 'BTN': 96.337696,
 'BWP': 14.390566,
 'BYN': 2.889388,
 'BZD': 2,
 'CAD': 1.409459,
 'CDF': 2277.763814,
 'CHF': 0.812218,
 'CLF': 0.023647,
 'CLP': 934.68866,
 'CNH': 6.767975,
 'CNY': 6.776686,
 'COP': 3250.798233,
 'CRC': 454.027923,
 'CUP': 24,
 'CVE': 96.670222,
 'CZK': 21.205386,
 'DJF': 177.721,
 'DKK': 6.542063,
 'DOP': 58.487939,
 'DZD': 133.229912,
 'EGP': 51.008475,
 'ERN': 15,
 'ETB': 160.33367,
 'EUR': 0.876691,
 'FJD': 2.22223,
 'FKP': 0.747079,
 'FOK': 6.542109,
 'GBP': 0.747063,
 'GEL': 2.627584,
 'GGP': 0.747079,
 'GHS': 11.594989,
 'GIP': 0.747079,
 'GMD': 74.412388,
 'GNF': 8782.205095,
 'GTQ': 7.631616,
 'GYD': 209.179097,
 'HKD': 7.842023,
 'HNL': 26.799781,
 'HRK': 6.605557,
 'HTG': 130.667411,
 'HUF': 316.957688,
 'IDR': 17905.298943,
 'ILS': 3.048643,
 'IMP': 0.747079,
 'INR': 96.339012,
 'IQD': 1309.378705,
 'IRR': 1353382.13832,
 'ISK': 125.226659,
 'JEP': 0.747079,
 'JMD': 158.627294,
 'JOD': 0.709,
 'JPY': 163.013007,
 'KES': 129.382422,
 'KGS': 87.451377,
 'KHR': 4048.568017,
 'KID': 1.42808,
 'KMF': 431.312127,
 'KRW': 1480.020746,
 'KWD': 0.309775,
 'KYD': 0.833333,
 'KZT': 468.495614,
 'LAK': 22431.530479,
 'LBP': 89500,
 'LKR': 336.190656,
 'LRD': 181.167029,
 'LSL': 16.461323,
 'LYD': 6.393734,
 'MAD': 9.378687,
 'MDL': 17.567872,
 'MGA': 4314.993562,
 'MKD': 53.842037,
 'MMK': 2102.646218,
 'MNT': 3607.087356,
 'MOP': 8.077185,
 'MRU': 40.059953,
 'MUR': 47.220323,
 'MVR': 15.448708,
 'MWK': 1745.497087,
 'MXN': 17.404263,
 'MYR': 4.088918,
 'MZN': 63.562138,
 'NAD': 16.461323,
 'NGN': 1377.172985,
 'NIO': 36.821579,
 'NOK': 9.633253,
 'NPR': 154.140313,
 'NZD': 1.715316,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.397041,
 'PGK': 4.47379,
 'PHP': 61.778739,
 'PKR': 278.003,
 'PLN': 3.794625,
 'PYG': 6055.67788,
 'QAR': 3.64,
 'RON': 4.588323,
 'RSD': 102.780119,
 'RUB': 78.486585,
 'RWF': 1471.350212,
 'SAR': 3.75,
 'SBD': 7.96279,
 'SCR': 14.000401,
 'SDG': 449.443084,
 'SEK': 9.699263,
 'SGD': 1.291588,
 'SHP': 0.747079,
 'SLE': 24.357914,
 'SLL': 24357.91394,
 'SOS': 571.930366,
 'SRD': 37.751053,
 'SSP': 4850.71167,
 'STN': 21.479349,
 'SYP': 121.76991,
 'SZL': 16.461323,
 'THB': 33.69783,
 'TJS': 9.238437,
 'TMT': 3.499985,
 'TND': 2.947032,
 'TOP': 2.38493,
 'TRY': 47.203836,
 'TTD': 6.768211,
 'TVD': 1.42808,
 'TWD': 32.34328,
 'TZS': 2628.102311,
 'UAH': 44.775914,
 'UGX': 3692.47881,
 'UYU': 40.270807,
 'UZS': 11930.641883,
 'VES': 737.2321,
 'VND': 26238.632049,
 'VUV': 118.972771,
 'WST': 2.706612,
 'XAF': 575.082836,
 'XCD': 2.7,
 'XCG': 1.79,
 'XDR': 0.7357,
 'XOF': 575.082836,
 'XPF': 104.619335,
 'YER': 238.142523,
 'ZAR': 16.461425,
 'ZMW': 18.372644,
 'ZWG': 26.7962,
 'ZWL': 26.7962}

In [9]:
type(api_data["rates"])  # This will show the type of the extracted rates data

dict

In [10]:
api_data.keys()  # This will display the keys of the main JSON response

dict_keys(['result', 'provider', 'documentation', 'terms_of_use', 'time_last_update_unix', 'time_last_update_utc', 'time_next_update_unix', 'time_next_update_utc', 'time_eol_unix', 'base_code', 'rates'])

### save the raw API response

In [11]:
import json 
from pathlib import Path

raw_folder = Path("../data/raw_data") 

raw_folder.mkdir(parents=True, exist_ok=True)

extraction_timestamp = datetime.now(timezone.utc)

raw_filename = (
    f"exchange_rates_"
    f"{extraction_timestamp:%Y%m%d_%H%M%S}.json"
) 

raw_path = raw_folder / raw_filename

with open(raw_path, "w", encoding="utf-8") as file:
    json.dump(api_data, file, indent=4) 
    
print(f"Raw response saved to: {raw_path}")

Raw response saved to: ..\data\raw_data\exchange_rates_20260722_161347.json

### Transformation

In [12]:
# Extract the business data 
rates = api_data["rates"]

# Display the data
rates

{'USD': 1,
 'AED': 3.6725,
 'AFN': 66.297576,
 'ALL': 82.088135,
 'AMD': 366.257897,
 'ANG': 1.79,
 'AOA': 929.484375,
 'ARS': 1477.7,
 'AUD': 1.428082,
 'AWG': 1.79,
 'AZN': 1.700145,
 'BAM': 1.714692,
 'BBD': 2,
 'BDT': 123.355712,
 'BGN': 1.714692,
 'BHD': 0.376,
 'BIF': 2992.937831,
 'BMD': 1,
 'BND': 1.291586,
 'BOB': 10.775878,
 'BRL': 5.077823,
 'BSD': 1,
 'BTN': 96.337696,
 'BWP': 14.390566,
 'BYN': 2.889388,
 'BZD': 2,
 'CAD': 1.409459,
 'CDF': 2277.763814,
 'CHF': 0.812218,
 'CLF': 0.023647,
 'CLP': 934.68866,
 'CNH': 6.767975,
 'CNY': 6.776686,
 'COP': 3250.798233,
 'CRC': 454.027923,
 'CUP': 24,
 'CVE': 96.670222,
 'CZK': 21.205386,
 'DJF': 177.721,
 'DKK': 6.542063,
 'DOP': 58.487939,
 'DZD': 133.229912,
 'EGP': 51.008475,
 'ERN': 15,
 'ETB': 160.33367,
 'EUR': 0.876691,
 'FJD': 2.22223,
 'FKP': 0.747079,
 'FOK': 6.542109,
 'GBP': 0.747063,
 'GEL': 2.627584,
 'GGP': 0.747079,
 'GHS': 11.594989,
 'GIP': 0.747079,
 'GMD': 74.412388,
 'GNF': 8782.205095,
 'GTQ': 7.631616,
 'GYD': 209.179097,
 'HKD': 7.842023,
 'HNL': 26.799781,
 'HRK': 6.605557,
 'HTG': 130.667411,
 'HUF': 316.957688,
 'IDR': 17905.298943,
 'ILS': 3.048643,
 'IMP': 0.747079,
 'INR': 96.339012,
 'IQD': 1309.378705,
 'IRR': 1353382.13832,
 'ISK': 125.226659,
 'JEP': 0.747079,
 'JMD': 158.627294,
 'JOD': 0.709,
 'JPY': 163.013007,
 'KES': 129.382422,
 'KGS': 87.451377,
 'KHR': 4048.568017,
 'KID': 1.42808,
 'KMF': 431.312127,
 'KRW': 1480.020746,
 'KWD': 0.309775,
 'KYD': 0.833333,
 'KZT': 468.495614,
 'LAK': 22431.530479,
 'LBP': 89500,
 'LKR': 336.190656,
 'LRD': 181.167029,
 'LSL': 16.461323,
 'LYD': 6.393734,
 'MAD': 9.378687,
 'MDL': 17.567872,
 'MGA': 4314.993562,
 'MKD': 53.842037,
 'MMK': 2102.646218,
 'MNT': 3607.087356,
 'MOP': 8.077185,
 'MRU': 40.059953,
 'MUR': 47.220323,
 'MVR': 15.448708,
 'MWK': 1745.497087,
 'MXN': 17.404263,
 'MYR': 4.088918,
 'MZN': 63.562138,
 'NAD': 16.461323,
 'NGN': 1377.172985,
 'NIO': 36.821579,
 'NOK': 9.633253,
 'NPR': 154.140313,
 'NZD': 1.715316,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.397041,
 'PGK': 4.47379,
 'PHP': 61.778739,
 'PKR': 278.003,
 'PLN': 3.794625,
 'PYG': 6055.67788,
 'QAR': 3.64,
 'RON': 4.588323,
 'RSD': 102.780119,
 'RUB': 78.486585,
 'RWF': 1471.350212,
 'SAR': 3.75,
 'SBD': 7.96279,
 'SCR': 14.000401,
 'SDG': 449.443084,
 'SEK': 9.699263,
 'SGD': 1.291588,
 'SHP': 0.747079,
 'SLE': 24.357914,
 'SLL': 24357.91394,
 'SOS': 571.930366,
 'SRD': 37.751053,
 'SSP': 4850.71167,
 'STN': 21.479349,
 'SYP': 121.76991,
 'SZL': 16.461323,
 'THB': 33.69783,
 'TJS': 9.238437,
 'TMT': 3.499985,
 'TND': 2.947032,
 'TOP': 2.38493,
 'TRY': 47.203836,
 'TTD': 6.768211,
 'TVD': 1.42808,
 'TWD': 32.34328,
 'TZS': 2628.102311,
 'UAH': 44.775914,
 'UGX': 3692.47881,
 'UYU': 40.270807,
 'UZS': 11930.641883,
 'VES': 737.2321,
 'VND': 26238.632049,
 'VUV': 118.972771,
 'WST': 2.706612,
 'XAF': 575.082836,
 'XCD': 2.7,
 'XCG': 1.79,
 'XDR': 0.7357,
 'XOF': 575.082836,
 'XPF': 104.619335,
 'YER': 238.142523,
 'ZAR': 16.461425,
 'ZMW': 18.372644,
 'ZWG': 26.7962,
 'ZWL': 26.7962}

In [13]:
# convert the rates dictionary to a DataFrame
exchange_rates = pd.DataFrame(list(rates.items()),columns=["currency", "exchange_rate"])
exchange_rates.head(10)  # Display the first few rows of the DataFrame

  currency  exchange_rate
0      USD       1.000000
1      AED       3.672500
2      AFN      66.297576
3      ALL      82.088135
4      AMD     366.257897
5      ANG       1.790000
6      AOA     929.484375
7      ARS    1477.700000
8      AUD       1.428082
9      AWG       1.790000

In [14]:
# Add base currency to every row
exchange_rates["base_currency"] = api_data["base_code"]

exchange_rates.head(10)

  currency  exchange_rate base_currency
0      USD       1.000000           USD
1      AED       3.672500           USD
2      AFN      66.297576           USD
3      ALL      82.088135           USD
4      AMD     366.257897           USD
5      ANG       1.790000           USD
6      AOA     929.484375           USD
7      ARS    1477.700000           USD
8      AUD       1.428082           USD
9      AWG       1.790000           USD

In [15]:
# Add extraction timestamp
exchange_rates["retrieved_at"] = api_data["time_last_update_utc"]

exchange_rates.head()

  currency  exchange_rate base_currency                     retrieved_at
0      USD       1.000000           USD  Wed, 22 Jul 2026 00:02:31 +0000
1      AED       3.672500           USD  Wed, 22 Jul 2026 00:02:31 +0000
2      AFN      66.297576           USD  Wed, 22 Jul 2026 00:02:31 +0000
3      ALL      82.088135           USD  Wed, 22 Jul 2026 00:02:31 +0000
4      AMD     366.257897           USD  Wed, 22 Jul 2026 00:02:31 +0000

In [16]:
exchange_rates

    currency  exchange_rate base_currency                     retrieved_at
0        USD       1.000000           USD  Wed, 22 Jul 2026 00:02:31 +0000
1        AED       3.672500           USD  Wed, 22 Jul 2026 00:02:31 +0000
2        AFN      66.297576           USD  Wed, 22 Jul 2026 00:02:31 +0000
3        ALL      82.088135           USD  Wed, 22 Jul 2026 00:02:31 +0000
4        AMD     366.257897           USD  Wed, 22 Jul 2026 00:02:31 +0000
..       ...            ...           ...                              ...
161      YER     238.142523           USD  Wed, 22 Jul 2026 00:02:31 +0000
162      ZAR      16.461425           USD  Wed, 22 Jul 2026 00:02:31 +0000
163      ZMW      18.372644           USD  Wed, 22 Jul 2026 00:02:31 +0000
164      ZWG      26.796200           USD  Wed, 22 Jul 2026 00:02:31 +0000
165      ZWL      26.796200           USD  Wed, 22 Jul 2026 00:02:31 +0000

[166 rows x 4 columns]

In [17]:
# Rearrange the columns 
exchange_rates = exchange_rates[ 
    [               
        "base_currency",
        "currency",
        "exchange_rate",
        "retrieved_at"
    ]
]

exchange_rates.head()

  base_currency currency  exchange_rate                     retrieved_at
0           USD      USD       1.000000  Wed, 22 Jul 2026 00:02:31 +0000
1           USD      AED       3.672500  Wed, 22 Jul 2026 00:02:31 +0000
2           USD      AFN      66.297576  Wed, 22 Jul 2026 00:02:31 +0000
3           USD      ALL      82.088135  Wed, 22 Jul 2026 00:02:31 +0000
4           USD      AMD     366.257897  Wed, 22 Jul 2026 00:02:31 +0000

In [18]:
exchange_rates.shape

(166, 4)

In [19]:
exchange_rates.dtypes

base_currency        str
currency             str
exchange_rate    float64
retrieved_at         str
dtype: object

In [20]:
# Display general DataFrame information
exchange_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   base_currency  166 non-null    str
 1   currency       166 non-null    str
 2   exchange_rate  166 non-null    float64
 3   retrieved_at   166 non-null    str
dtypes: float64(1), str(3)
memory usage: 5.3 KB

In [21]:
# Check for missing values
exchange_rates.isnull().sum()

base_currency    0
currency         0
exchange_rate    0
retrieved_at     0
dtype: int64

In [22]:
# Check for duplicate rows
exchange_rates.duplicated().sum()

np.int64(0)

##### The API returns data in JSON format, where the exchange rates are stored as a Python dictionary. While dictionaries are excellent for storing key-value pairs, they are not ideal for data analysis. By converting the dictionary into a Pandas DataFrame, we transform the data into rows and columns, making it easier to explore, clean, export as CSV, and load into PostgreSQL for analysis. This transformation step is a core part of every ETL pipeline.
##### N.B: 
- Dictionary: useful for API transport and key-value storage.
- DataFrame: useful for structured cleaning, analysis and database loading.

##### The Transformation step of the ETL pipeline has been completed. The API returned a nested JSON object, but the business data (rates) has been extracted and transformed into a structured Pandas DataFrame. The data is now in a format that is ready for exploration, cleaning, validation, and eventually loading into the database(PostgreSQL).

In [23]:
exchange_rates

    base_currency currency  exchange_rate                     retrieved_at
0             USD      USD       1.000000  Wed, 22 Jul 2026 00:02:31 +0000
1             USD      AED       3.672500  Wed, 22 Jul 2026 00:02:31 +0000
2             USD      AFN      66.297576  Wed, 22 Jul 2026 00:02:31 +0000
3             USD      ALL      82.088135  Wed, 22 Jul 2026 00:02:31 +0000
4             USD      AMD     366.257897  Wed, 22 Jul 2026 00:02:31 +0000
..            ...      ...            ...                              ...
161           USD      YER     238.142523  Wed, 22 Jul 2026 00:02:31 +0000
162           USD      ZAR      16.461425  Wed, 22 Jul 2026 00:02:31 +0000
163           USD      ZMW      18.372644  Wed, 22 Jul 2026 00:02:31 +0000
164           USD      ZWG      26.796200  Wed, 22 Jul 2026 00:02:31 +0000
165           USD      ZWL      26.796200  Wed, 22 Jul 2026 00:02:31 +0000

[166 rows x 4 columns]

### DATA CLEANING: Although this API returns relatively clean data, every ETL pipeline should validate its input before loading it into a database.

In [24]:
# Check for Blanks
(exchange_rates == "").sum()

base_currency    0
currency         0
exchange_rate    0
retrieved_at     0
dtype: int64

In [25]:
# Recheck missing values
exchange_rates.isnull().sum()

base_currency    0
currency         0
exchange_rate    0
retrieved_at     0
dtype: int64

In [26]:
# Validate positive exchange rates
(exchange_rates["exchange_rate"] <= 0).sum()

np.int64(0)

In [ ]:
# Standardize the currency to uppercase and remove any leading or trailing whitespace
exchange_rates["currency"] = (
    exchange_rates["currency"]
    .str.strip()
    .str.upper()
)

In [29]:
# Standardize the base currency to uppercase and remove any leading or trailing whitespace
exchange_rates["base_currency"] = (
    exchange_rates["base_currency"]
    .str.strip()
    .str.upper()
)

In [30]:
# Ensure exchange_rate column is numeric, converting any non-numeric values to NaN
exchange_rates["exchange_rate"] = pd.to_numeric(
    exchange_rates["exchange_rate"],
    errors="coerce" # Turns values that cannot be converted into NaN
)

In [31]:
exchange_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   base_currency  166 non-null    str
 1   currency       166 non-null    str
 2   exchange_rate  166 non-null    float64
 3   retrieved_at   166 non-null    str
dtypes: float64(1), str(3)
memory usage: 5.3 KB

In [32]:
# Convert retrieved_at to datetime data type
exchange_rates["retrieved_at"] = pd.to_datetime(
    exchange_rates["retrieved_at"],
    errors="coerce",
    utc=True
)

In [33]:
exchange_rates.dtypes

base_currency                    str
currency                         str
exchange_rate                float64
retrieved_at     datetime64[us, UTC]
dtype: object

### Business Validation: It is not enough to clean and transform data, business validation is equally important
### Introduces checks that confirm whether the data makes sense from a business perspective.

In [34]:
# Count unique currency 
exchange_rates["currency"].nunique() # .nunique() counts distinct non-null values. 

# If there are 166 rows and 166 unique currency codes, each currency appears once in this API snapshot.

166

In [36]:
# Check duplicate currency codes 
# This checks duplicates using only the currency-code column.
# It differs from Cell 33, which checked duplicates across entire rows.
exchange_rates["currency"].duplicated().sum()

np.int64(0)

In [37]:
# Find the ten smallest rates
exchange_rates.nsmallest(10, "exchange_rate") # .nsmallest() retrieves rows with the lowest numeric values. 10 specifies the number of rows. "exchange_rate" specifies the ranking column.

    base_currency currency  exchange_rate              retrieved_at
29            USD      CLF       0.023647 2026-07-22 00:02:31+00:00
80            USD      KWD       0.309775 2026-07-22 00:02:31+00:00
15            USD      BHD       0.376000 2026-07-22 00:02:31+00:00
109           USD      OMR       0.384497 2026-07-22 00:02:31+00:00
72            USD      JOD       0.709000 2026-07-22 00:02:31+00:00
158           USD      XDR       0.735700 2026-07-22 00:02:31+00:00
49            USD      GBP       0.747063 2026-07-22 00:02:31+00:00
47            USD      FKP       0.747079 2026-07-22 00:02:31+00:00
51            USD      GGP       0.747079 2026-07-22 00:02:31+00:00
53            USD      GIP       0.747079 2026-07-22 00:02:31+00:00

In [38]:
# Find the ten largest rates
# Returns the ten highest numeric exchange-rate values.
# These are the highest quoted rates relative to USD.
# A large value means one US dollar converts into many units of that currency, but denomination differences mean this alone is not a complete measure of economic strength. 
exchange_rates.nlargest(10, "exchange_rate")

    base_currency currency  exchange_rate              retrieved_at
68            USD      IRR   1.353382e+06 2026-07-22 00:02:31+00:00
84            USD      LBP   8.950000e+04 2026-07-22 00:02:31+00:00
152           USD      VND   2.623863e+04 2026-07-22 00:02:31+00:00
130           USD      SLL   2.435791e+04 2026-07-22 00:02:31+00:00
83            USD      LAK   2.243153e+04 2026-07-22 00:02:31+00:00
63            USD      IDR   1.790530e+04 2026-07-22 00:02:31+00:00
150           USD      UZS   1.193064e+04 2026-07-22 00:02:31+00:00
55            USD      GNF   8.782205e+03 2026-07-22 00:02:31+00:00
116           USD      PYG   6.055678e+03 2026-07-22 00:02:31+00:00
133           USD      SSP   4.850712e+03 2026-07-22 00:02:31+00:00

## Export Clean Data

In [39]:
exchange_rates.to_csv(  #Writes the DataFrame to a comma-separated values file.
    "../data/cleaned_data/exchange_rates.csv", index=False) # Destination path. Moves from the notebooks directory to the project root, then into: data/cleaned_data/

print("Export successful.") # Displays a confirmation message

Export successful.

### The PostgreSQL connection stage;
### The database-loading stage.

## Load the cleaned data into Postgres

In [40]:
# Load the environment variables from the .env file

load_dotenv("../.env", override=True) # ../.env points to the project-root .env file from the notebook directory. override=True replaces any previously loaded values with the current contents of the file.

print("Database user:", os.getenv("DB_USER"))
print("Database host:", os.getenv("DB_HOST"))
print("Database name:", os.getenv("DB_NAME"))
print("Password loaded:", bool(os.getenv("DB_PASSWORD")))

Database user: postgres
Database host: localhost
Database name: FINTECH_API_PIPELINE_DB
Password loaded: True

In [41]:
# Create the engine for PostgreSQL connection using SQLAlchemy 
from sqlalchemy import URL, create_engine # URL safely constructs the database connection URL. 'create_engine' creates the SQLAlchemy engine.

# Connection URL
DATABASE_URL = URL.create( # Creates a structured connection configuration.
    drivername="postgresql+psycopg2", # use PostgreSQL; connect through the psycopg2 Python driver.
    
    # Credentials are loaded from environment variables, which are set in the .env file.
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME")
)

# Creates Engine
engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True # Creates a reusable SQLAlchemy engine. 'pool_pre_ping' checks pooled connections before reusing them. If a stale connection is detected, SQLAlchemy replaces it.
)

# Display the engine to confirm successful creation
print(engine)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/FINTECH_API_PIPELINE_DB)

In [42]:
# Test the connection to PostgreSQL

from sqlalchemy import text # Imports the function used to wrap a SQL statement.

try:
    with engine.connect() as conn: # 'engine.connect()' establishes the real PostgreSQL connection. 'with' ensures the connection is automatically closed afterward. 'conn' represents the active connection.
        
        result = conn.execute(         # The SQL statement requests: the connected database; the authenticated PostgreSQL user; the PostgreSQL server version.
            text("SELECT current_database(), current_user, version();")
        )
        print(result.fetchone()) # .fetchone() retrieves the first result row.

    print("PostgreSQL connection successful.")

except Exception as error: # Catches connection, authentication and SQL errors.
    print("PostgreSQL connection failed:") # Provides a readable error message for debugging.
    print(error)

('FINTECH_API_PIPELINE_DB', 'postgres', 'PostgreSQL 18.4 on x86_64-windows, compiled by msvc-19.44.35226, 64-bit')
PostgreSQL connection successful.

##### The Extract and Transform process have been completed

## Load the DataFrame to Postgres

In [43]:
# Load the transformed exchange-rate data into PostgreSQL
rows_loaded = exchange_rates.to_sql( # 'exchange_rates.sql' Sends the DataFrame to a relational database through SQLAlchemy.
    name="exchange_rates", # Creates a PostgreSQL table called exchange_rates
    con=engine, # Tells Pandas which database engine to use.
    if_exists="replace", # This line deletes existing exchange_rates table that already exists and create a new table and loads the current DataFrames into it. Alternatives are, if_exists="append" (adds new rows to the existing table) or if_exists="fail" (raises an error if the table already exists).
    index=False # Prevents the Pandas row index from becoming a PostgreSQL column.
)

print(f"{rows_loaded} rows loaded successfully.")

166 rows loaded successfully.

### Load Verification

In [44]:
# Verify the load from python
verification = pd.read_sql(  # Executes a SQL query and returns the result as a DataFrame.
    """
    SELECT COUNT(*) AS total_rows
    FROM exchange_rates;
    """,
    con=engine  # Executes the query through your PostgreSQL engine.
)

verification

   total_rows
0         166

In [45]:
pd.read_sql(
    """
    SELECT *
    FROM exchange_rates
    LIMIT 10;
    """,
    con=engine
)

  base_currency currency  exchange_rate              retrieved_at
0           USD      USD       1.000000 2026-07-22 00:02:31+00:00
1           USD      AED       3.672500 2026-07-22 00:02:31+00:00
2           USD      AFN      66.297576 2026-07-22 00:02:31+00:00
3           USD      ALL      82.088135 2026-07-22 00:02:31+00:00
4           USD      AMD     366.257897 2026-07-22 00:02:31+00:00
5           USD      ANG       1.790000 2026-07-22 00:02:31+00:00
6           USD      AOA     929.484375 2026-07-22 00:02:31+00:00
7           USD      ARS    1477.700000 2026-07-22 00:02:31+00:00
8           USD      AUD       1.428082 2026-07-22 00:02:31+00:00
9           USD      AWG       1.790000 2026-07-22 00:02:31+00:00

In [46]:
exchange_rates["retrieved_at"] = pd.to_datetime(
    exchange_rates["retrieved_at"],
    utc=True
)

exchange_rates.dtypes

base_currency                    str
currency                         str
exchange_rate                float64
retrieved_at     datetime64[us, UTC]
dtype: object